### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by mohsenyaghoobi** [wialon/gmqtt#49]
Does anybody know what is this error!

/home/mohsen/PycharmProjects/gmqtt/venv/bin/python /home/mohsen/PycharmProjects/gmqtt/gmqtt.py
Traceback (most recent call last):
  File "/home/mohsen/PycharmProjects/gmqtt/gmqtt.py", line 59, in <module>
    loop.run_until_complete(main(host, token))
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/home/mohsen/PycharmProjects/gmqtt/gmqtt.py", line 41, in main
    client.set_auth_credentials(token, None)
  File "/home/mohsen/PycharmProjects/gmqtt/gmqtt/client.py", line 116, in set_auth_credentials
    self._username = username.encode()
AttributeError: 'NoneType' object has no attribute 'encode'
Task was destroyed but it is pending!
task: <Task pending coro=<Client._resend_qos_messages() running at /home/mohsen/PycharmProjects/gmqtt/gmqtt/client.py:83> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f41ed8fe918>()]>>

**Comment by Mixser** [comment]
Hi @mohsenyaghoobi 
Please, check what you passed to `client.set_auth_credentials` method. It seem to be you pass `None` value.

**Comment by Lenka42** [comment]
@mohsenyaghoobi I'm closing this issue. If you have any questions regarding authorization, please reopen.
